AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

  Include:
    - 'Rakefile'
    - 'bin/test'

  NewCops: enable

# Naming ------------------------------------

Naming/FileName:
  Exclude:
    - lib/slack-notifier.rb
    - spec/lib/slack-notifier_spec.rb
    - slack-notifier.gemspec
    - Gemfile

# Style ------------------------------------

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'

# Layout ----------------------------------

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/DotPosition:
  EnforcedStyle: leading

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 128
# Metrics ----------------------------------

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

# Lint -------------------------------------
